development:
  adapter: postgresql
  database: frank_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fran_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: frank_production
  pool: 5
  timeout: 500